version: "3.7"

services:
  api:
    image: hello-world-php
    ports:
      - 8000:8000
    working_dir: /api
    volumes:
      - ./:/api
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: hello_world
  mysql:
    image: mysql:5.7
    volumes:
      - hello-world-php-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello_world
volumes:
  hello-world-php-mysql-data: